import { User, Publication, Comment, Message, Conversation } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    auth_id: 'auth-1',
    username: 'joaosilva',
    email: 'joao@email.com',
    full_name: 'João Silva',
    bio: 'Criador de conteúdo de áudio 🎙️ | Podcast sobre tecnologia e inovação',
    avatar_url: null,
    cover_url: null,
    is_private: false,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    followers_count: 1234,
    following_count: 456,
    publications_count: 89,
  },
  {
    id: 'user-2',
    auth_id: 'auth-2',
    username: 'mariasantos',
    email: 'maria@email.com',
    full_name: 'Maria Santos',
    bio: 'Professora e podcaster 📚 | Educação que transforma vidas',
    avatar_url: null,
    cover_url: null,
    is_private: false,
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-16T10:00:00Z',
    followers_count: 892,
    following_count: 234,
    publications_count: 45,
  },
  {
    id: 'user-3',
    auth_id: 'auth-3',
    username: 'carlosmusic',
    email: 'carlos@email.com',
    full_name: 'Carlos Oliveira',
    bio: 'Músico e compositor 🎵 | Compartilhando melodias do coração',
    avatar_url: null,
    cover_url: null,
    is_private: false,
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-17T10:00:00Z',
    followers_count: 3456,
    following_count: 789,
    publications_count: 123,
  },
  {
    id: 'user-4',
    auth_id: 'auth-4',
    username: 'anafunny',
    email: 'ana@email.com',
    full_name: 'Ana Lima',
    bio: 'Stand-up comedian 😂 | Rindo da vida desde 1995',
    avatar_url: null,
    cover_url: null,
    is_private: false,
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-18T10:00:00Z',
    followers_count: 5678,
    following_count: 321,
    publications_count: 67,
  },
  {
    id: 'user-5',
    auth_id: 'auth-5',
    username: 'techbr',
    email: 'tech@email.com',
    full_name: 'Tech Brasil',
    bio: 'Notícias e análises de tecnologia 💻 | O futuro acontece aqui',
    avatar_url: null,
    cover_url: null,
    is_private: false,
    created_at: '2024-01-19T10:00:00Z',
    updated_at: '2024-01-19T10:00:00Z',
    followers_count: 12000,
    following_count: 156,
    publications_count: 234,
  },
]

export const MOCK_CURRENT_USER: User = {
  id: 'current-user',
  auth_id: 'auth-current',
  username: 'voce',
  email: 'voce@email.com',
  full_name: 'Você',
  bio: 'Meu primeiro dia no VozZap! 🎙️',
  avatar_url: null,
  cover_url: null,
  is_private: false,
  created_at: '2024-01-20T10:00:00Z',
  updated_at: '2024-01-20T10:00:00Z',
  followers_count: 0,
  following_count: 0,
  publications_count: 0,
}

export const MOCK_PUBLICATIONS: Publication[] = [
  {
    id: 'pub-1',
    user_id: 'user-3',
    title: 'Nova composição: "Pôr do Sol em Ipanema"',
    description: 'Composta ontem à noite, inspirada nas cores do Rio de Janeiro. Violão acústico e alma brasileira.',
    category: 'musica',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 187,
    visibility: 'public',
    likes_count: 342,
    comments_count: 28,
    plays_count: 1567,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    users: MOCK_USERS[2],
    hasLiked: false,
  },
  {
    id: 'pub-2',
    user_id: 'user-1',
    title: 'Ep. 47 - O futuro da IA no Brasil',
    description: 'Neste episódio discutimos como a inteligência artificial está transformando o mercado de trabalho brasileiro e quais habilidades serão valorizadas.',
    category: 'podcast',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 2847,
    visibility: 'public',
    likes_count: 891,
    comments_count: 67,
    plays_count: 12450,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    users: MOCK_USERS[0],
    hasLiked: true,
  },
  {
    id: 'pub-3',
    user_id: 'user-4',
    title: 'Por que o WiFi da minha casa me odeia?',
    description: 'Uma reflexão profunda sobre a relação conturbada entre humanos e roteadores domésticos. 😂',
    category: 'comedia',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 423,
    visibility: 'public',
    likes_count: 2341,
    comments_count: 189,
    plays_count: 34560,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    users: MOCK_USERS[3],
    hasLiked: false,
  },
  {
    id: 'pub-4',
    user_id: 'user-2',
    title: 'Aula: Como aprender qualquer coisa em 20 horas',
    description: 'O método comprovado de Josh Kaufman para adquirir qualquer nova habilidade rapidamente. Aplicações práticas para o dia a dia.',
    category: 'educacao',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 1843,
    visibility: 'public',
    likes_count: 567,
    comments_count: 43,
    plays_count: 8900,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    users: MOCK_USERS[1],
    hasLiked: false,
  },
  {
    id: 'pub-5',
    user_id: 'user-5',
    title: 'Breaking: Apple anuncia MacBook com IA integrada',
    description: 'Análise completa do novo MacBook Pro com chip M4 Pro e capacidades de IA rodando localmente no dispositivo.',
    category: 'podcast',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 634,
    visibility: 'public',
    likes_count: 1234,
    comments_count: 98,
    plays_count: 23400,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    users: MOCK_USERS[4],
    hasLiked: true,
  },
  {
    id: 'pub-6',
    user_id: 'user-3',
    title: 'Improvisando no jazz - take 3',
    description: 'Sessão de improviso com piano, contrabaixo e bateria. Gravado ao vivo no nosso estúdio.',
    category: 'musica',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 312,
    visibility: 'public',
    likes_count: 445,
    comments_count: 34,
    plays_count: 5670,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    users: MOCK_USERS[2],
    hasLiked: false,
  },
  {
    id: 'pub-7',
    user_id: 'user-1',
    title: 'Minha rotina matinal de produtividade',
    description: 'Como organizo minha manhã para ser mais produtivo. Dicas práticas que me transformaram.',
    category: 'fala',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.mp3',
    duration: 756,
    visibility: 'public',
    likes_count: 789,
    comments_count: 56,
    plays_count: 15600,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    users: MOCK_USERS[0],
    hasLiked: true,
  },
]

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    user_id: 'user-1',
    publication_id: 'pub-1',
    content: 'Que composição incrível! Me lembrou muito do Tom Jobim. 🎶',
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    user: MOCK_USERS[0],
  },
  {
    id: 'comment-2',
    user_id: 'user-2',
    publication_id: 'pub-1',
    content: 'Amei! Quando vai ter um show ao vivo? 🎸',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    user: MOCK_USERS[1],
  },
  {
    id: 'comment-3',
    user_id: 'user-4',
    publication_id: 'pub-1',
    content: 'Top demais! Compartilhei com todo mundo 🔥',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    user: MOCK_USERS[3],
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    sender_id: 'user-1',
    recipient_id: 'current-user',
    content: 'Oi! Vi seu perfil no VozZap, seus áudios são incríveis!',
    message_type: 'text',
    audio_url: null,
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    sender: MOCK_USERS[0],
    recipient: MOCK_CURRENT_USER,
  },
  {
    id: 'msg-2',
    sender_id: 'current-user',
    recipient_id: 'user-1',
    content: 'Obrigado! Adoro seu podcast também! 🎙️',
    message_type: 'text',
    audio_url: null,
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    sender: MOCK_CURRENT_USER,
    recipient: MOCK_USERS[0],
  },
  {
    id: 'msg-3',
    sender_id: 'user-1',
    recipient_id: 'current-user',
    content: 'Quer fazer uma collab? Tenho uma ideia incrível para um episódio!',
    message_type: 'text',
    audio_url: null,
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    sender: MOCK_USERS[0],
    recipient: MOCK_CURRENT_USER,
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    user_one_id: 'current-user',
    user_two_id: 'user-1',
    last_message_id: 'msg-3',
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    user_one: MOCK_CURRENT_USER,
    user_two: MOCK_USERS[0],
    last_message: MOCK_MESSAGES[2],
    unread_count: 1,
  },
  {
    id: 'conv-2',
    user_one_id: 'current-user',
    user_two_id: 'user-3',
    last_message_id: null,
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    user_one: MOCK_CURRENT_USER,
    user_two: MOCK_USERS[2],
    last_message: undefined,
    unread_count: 0,
  },
]

export const MOCK_FOLLOWING = ['user-1', 'user-3']
